markdown: kramdown
permalink: /:title/
url: http://strstr.io
name: STRSTR.IO
author: StrSTR
github: goingeast
safe: true
paginate: 20
about: "Stay hungry, stay foolish."

theme: jekyll-theme-midnight
